version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ultra-secret-pwd-for-as-root
      MYSQL_DATABASE: cards
      MYSQL_USER: my-user    # Crear un usuario my-user
      MYSQL_PASSWORD: ultra-secret-pwd-for-as  # Establecer la contraseña del usuario my-user

  javalin-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: javalin-app-container
    ports:
      - "8080:8080" # Exponer solo el puerto de la aplicación Java
    environment:
      JDBC_URL: jdbc:mysql://db:3306/cards  # Conectar a MySQL usando el nombre del servicio 'db'
      JDBC_USER: my-user
      JDBC_PASSWORD: ultra-secret-pwd-for-as
    depends_on:
      - db  # Especificar que depende del servicio db
