#this file is necessary for execute the program
# ebean configuration
ebean:
  dumpMetricsOnShutdown: true
  dumpMetricsOptions: loc,sql,hash
  ddl:
    generate: true
    run: true
  debug:
    sql: true
    lazy load: true
  logging: all
  transient-init-error: false

# database configuration
datasource:
  db:
    username: ""
    password: ""
    platform: sqlite # h2, postgres, mysql, oracle, sqlserver
    ddlMode: dropCreate # none | dropCreate | migrations
    dbName: Cards
    url: jdbc:sqlite:Cards.db