# ebean configuration
ebean:
  dumpMetricsOnShutdown: true
  dumpMetricsOptions: loc,sql,hash
  ddl:
    generate: true
    run: true
  debug:
    sql: true
    lazyLoad: true
  logging: all
  transient-init-error: false

datasource:
  db:
    username: "root"  # Usuario de MySQL
    password: "Estoy"  # Contraseña de MySQL
    platform: mysql  # Tipo de plataforma de base de datos
    ddlMode: dropCreate  # Modo de creación de tablas (puedes ajustarlo según tus necesidades)
    dbName: cards  # Nombre de la base de datos en MySQL
    url: jdbc:mysql://localhost:3306/cards  # URL de conexión JDBC para MySQL
    driver: com.mysql.cj.jdbc.Driver  # Driver JDBC para MySQL